Adapt wazuh-ansible to new 4.0 major version
wazuh/wazuh-ansible pull request #458
Opened 2020-08-26 11:09 UTC by Zenidd

Hi team, 

This PR adapts wazuh-ansible to the latest changes on new Wazuh 4.0 version.
This PR is related to #454 and #457 

Greetings,

JP

2020-08-26 12:10 UTC, manuasir approved these changes
This looks good!

2020-08-28 10:36 UTC, xr09 requested changes
Remember to update the VERSION and CHANGELOG files.

2020-10-06 13:50 UTC, manuasir requested changes
We should set the latest URL packages here

2020-10-27 15:10 UTC, manuasir approved these changes

2020-10-27 15:10 UTC, merged