630 Release 4.2.2 Ansible
wazuh/wazuh-ansible pull request #632
Opened 2021-09-30 15:42 UTC by lastranikos

This PR close #630

2021-09-30 18:16 UTC, teddytpc1 approved these changes
LGTM

2021-09-30 21:07 UTC, rauldpm requested changes
Minor changes

2021-09-30 21:07 UTC, rauldpm commented on README.md
>  | v4.2.0        | 7.10.2  | 1.13.2 |
There is no v4.2.2?

2021-10-01 12:08 UTC, teddytpc1 requested changes

2021-10-01 12:08 UTC, teddytpc1 commented on CHANGELOG.md
>  ## [v4.2.0]
Same comment as Raul's in the README.md. 4.2.2 should be listed in this file.

2021-10-01 15:33 UTC, closed without merging

2021-10-01 15:33 UTC, lastranikos commented
This PR is fixed at https://github.com/wazuh/wazuh-ansible/pull/635