630merge 4.2 to stable
wazuh/wazuh-ansible pull request #634
Opened 2021-09-30 20:53 UTC by lastranikos

This PR close #630

2021-09-30 21:06 UTC, rauldpm requested changes
Minor changes

2021-09-30 21:06 UTC, rauldpm commented on roles/elastic-stack/ansible-kibana/templates/kibana.yml.j2
> +{% endif %}
Duplicated?

2021-10-01 08:54 UTC, alberpilot approved these changes

2021-10-01 08:56 UTC, alberpilot commented on roles/elastic-stack/ansible-kibana/templates/kibana.yml.j2
> +{% endif %}
Don't think so
![image](https://user-images.githubusercontent.com/3830293/135593396-1803e250-3aff-4f31-b73d-adcea0329816.png)

2021-10-01 08:57 UTC, merged