Fix to be able to set complex passwords with symbols too
wazuh/wazuh-ansible pull request #794
Opened 2022-06-09 09:37 UTC by TuningYourCode

This PR fixes the issue that it's currently not possible to set complex passwords for admin / kibanaserver user which include (special) symbols like `.#*,` etc.

2022-06-09 14:20 UTC, teddytpc1 commented
Hi @TuningYourCode.
Can you please create another PR using branch `4.3`? Meanwhile I will be testing the changes using that branch.
Thanks.

2022-06-09 15:38 UTC, teddytpc1 commented
Hi @TuningYourCode. 
This [line](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-filebeat-oss/templates/filebeat.yml.j2#L24) should also be modified to include the single quotes for the `indexer_security_password` variable.

2022-06-09 15:41 UTC, teddytpc1 requested changes
Hi @TuningYourCode. 
This [line](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-filebeat-oss/templates/filebeat.yml.j2#L24) should also be modified to include the single quotes for the `indexer_security_password` variable.

2022-06-09 15:51 UTC, TuningYourCode commented
done despite not really required as long as you don't do scary things where the yaml parser would cast the string to something else like `yes` / `no` `3.14` etc.

2022-06-09 18:31 UTC, teddytpc1 approved these changes
LGTM

2022-06-13 12:41 UTC, vcerenu approved these changes
LGTM

2022-06-13 12:50 UTC, merged