Merge v4.3.6 into master
wazuh/wazuh-ansible pull request #822
Opened 2022-07-22 15:18 UTC by teddytpc1

This PR merges `v.4.3.6` into `master`.

2022-07-22 16:58 UTC, vcerenu approved these changes
LGTM

2022-07-25 10:44 UTC, okynos requested changes
Minor fix

2022-07-25 10:44 UTC, okynos commented on roles/wazuh/wazuh-dashboard/vars/debian.yml
> +>>>>>>> master
Fix this.

2022-07-25 11:07 UTC, teddytpc1 commented on roles/wazuh/wazuh-dashboard/vars/debian.yml
> +>>>>>>> master
Fixed. Thanks.

2022-07-25 11:20 UTC, okynos approved these changes

2022-07-25 11:20 UTC, merged